# Generated by Django 6.0.1 on 2026-01-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Đánh dấu ẩn (do admin ẩn hoặc bị report)'),
        ),
    ]
